<?php
//require_once ('config/cfg.php');
require __DIR__ . '/vendor/autoload.php';
require_once  './lib/nusoap/nusoap.php';
use \Curl\Curl;

        include("xmlrpc.inc");
        include("xmlrpcs.inc");

        class xmlrpc_server_methods_container
        {
                /*
                * Method used to test logging of php warnings generated by user functions.
                */
                function phpwarninggenerator($m)
                {
//error_log("phpwarninggenerator ".print_r($b,true));
                        $a = $b; // this triggers a warning in E_ALL mode, since $b is undefined
                        return new xmlrpcresp(new xmlrpcval(1, 'boolean'));
                }
        }

      	 $onephone_iphone_login_sig=array(array($xmlrpcArray,$xmlrpcString,$xmlrpcString,$xmlrpcString,$xmlrpcString,$xmlrpcBase64));
        $onephone_iphone_login_doc='onephone_iphone_login function';
        function onephone_iphone_login($m)
        {
		 global $db;

		$ret = "ERROR";
		$err="";
              $temp = "";
              $temp=$m->getParam(0);
              $username=$temp->scalarval();

              $temp=$m->getParam(1);
              $domain=$temp->scalarval();

              $temp=$m->getParam(2);
              $password=$temp->scalarval();

              $temp=$m->getParam(3);
              $token=$temp->scalarval();
              /*
              if ( $username == "xtest2")
               {
                    //$arrX["user"] = "0879114114"; //"102";
                    $arrX["user"] = "102";
                    $arrX["password"] = "100_WEjhjgyyte111";
                    $arrX["domain"] = "14.1.28.210";
                    $arrX["sipchat"] = "http://14.1.28.210/im";
                    $arrX["url_home"] = "https://vndig.com";
                    $arrX["url_services"] = "https://vndig.com";
                    $arrX["transport"] = "UDP";
                    $arrX["xmppserver"] = "http://comm.lotus-asia.net";
                    $arrX["liveserver"] = "rtmp://vndig.com/show/";
                    $arrX["signalserver"] = "https://vndig.com/signal/index.php";
                    $arrX["apisecret"] = "123sAAAA";
                    $arrX["socialurl"] = "http://social.onephone.online";
                    $arrX["shopurl"] = "http://shops.onephone.online";
                    $arrX["shopapisecret"] = "api123";
                    $arrX["certpayment"] = "kgakbj@#$#$#kkwqhkwqkjr23423jkwqgrkwqgrkqwrwqrqw";
                    $arrX["status"] = "OK";
                    
                    return new xmlrpcresp(new xmlrpcval(json_encode($arrX), "string"));
               
               }
              */
		$ret = "OK";	//"ERROR_ACCOUNT_ALREADY_ACTIVATED";
		$arrX = array();

		$arrX = errorDefault($username." ".$password);
		$access_token =  "aYDLsN8GrF4WrjisMvSUbzP3";
		$curl = new Curl();
		$curl->get('http://vndig.com/social/index.php', array(
		    		'r' => 'api/user/login',
		    		'access_token' => $access_token,
		    		'username' => $username,
		    		'password' => $password,
				));
		$c_userid = -1;
		$c_guid  = "";
		if ($curl->error) {
		    		//error_log( 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n");
				$arrX = errorDefault($username." ".$password." -LOGIN");
				return new xmlrpcresp(new xmlrpcval(json_encode($arrX), "string"));
				exit;		
		} else {
		    		error_log( 'Response: (NO ERROR)' . "\n");
				//error_log(print_r($curl->response,true));

				$c_userid  =$curl->response->id;
				$c_guid = $curl->response->guid;
		}
		if ( (  $c_guid == "" ) || (  $c_guid == "" ) )
		{
		    		//error_log( 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n");
				$arrX = errorDefault($username." ".$password." -LOGIN-FAIL");
				return new xmlrpcresp(new xmlrpcval(json_encode($arrX), "string"));
				exit;		
		}

		$c_onephone  = "";
		$c_guid = str_replace("-","",$c_guid);
        $c_guid = substr($c_guid,0,10);
		error_log(print_r($c_guid,true));
		$curl->get('http://vndig.com/social/index.php', array(
			    'r' => 'api/profile/view',
			    'access_token' => $access_token,
			    'id' => $c_userid,
			));
		if ($curl->error) {
		    		error_log( 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n");
				$arrX = errorDefault($username." ".$password." -PROFILE");
				return new xmlrpcresp(new xmlrpcval(json_encode($arrX), "string"));

				exit;		
		} else {
			    	error_log( 'Response:' . "\n");
				error_log(print_r($curl->response,true));
				$c_onephone = $curl->response->onephone;
		}
		$arrX["user"] = $c_onephone;
		$arrX["password"] = $c_guid;
		//$arrX["domain"] = "globalsip.lotus-asia.net:5070";
        //$arrX["domain"] = "sip.vndig.com:5060"; 14.1.28.210
        $arrX["domain"] = "14.1.28.210"; 
        $arrX["sipchat"] = "http://vndig.com/im/";
		//$arrX["sipchat"] = "http://globalsip.lotus-asia.net/im/";
		$arrX["url_home"] = "https://vndig.com";
		$arrX["url_services"] = "http://device.onephone.online";
		$arrX["transport"] = "UDP";
		$arrX["xmppserver"] = "http://comm.lotus-asia.net";
		$arrX["liveserver"] = "rtmp://vndig.com/show/";
			$arrX["signalserver"] = "https://vndig.com/signal/index.php";
			$arrX["apisecret"] = "123sAAAA";
			$arrX["socialurl"] = "http://social.onephone.online";
			$arrX["shopurl"] = "http://shops.onephone.online";
			$arrX["shopapisecret"] = "api123";
			$arrX["certpayment"] = "kgakbj@#$#$#kkwqhkwqkjr23423jkwqgrkwqgrkqwrwqrqw";
		$arrX["status"] = "OK";
error_log(print_r($arrX,true));        
		return new xmlrpcresp(new xmlrpcval(json_encode($arrX), "string"));

	}

	function errorDefault($shopapisecret)
	{
			$arrX["user"] = "";
			$arrX["password"] = "";
			$arrX["domain"] = "";
			$arrX["sipchat"] = "";
			$arrX["url_home"] = "";
			$arrX["url_services"] = "";
			$arrX["transport"] = "";
			$arrX["xmppserver"] = "";
			$arrX["liveserver"] = "";
			$arrX["signalserver"] = "";
			$arrX["apisecret"] = "";
			$arrX["socialurl"] = "";
			$arrX["shopurl"] = "";
			$arrX["shopapisecret"] = $shopapisecret;
			$arrX["certpayment"] = "";
			$arrX["status"] = "ERROR";
			return $arrX;
	}
      	 $onephone_android_login_sig=array(array($xmlrpcArray,$xmlrpcString,$xmlrpcString,$xmlrpcString,$xmlrpcString));
        $onephone_android_login_doc='onephone_android_login function';
        function onephone_android_login($m)
        {
		 global $db;

		$ret = "ERROR";
		$err="";
              $temp = "";
              $temp=$m->getParam(0);
              $username=$temp->scalarval();

              $temp=$m->getParam(1);
              $domain=$temp->scalarval();

              $temp=$m->getParam(2);
              $password=$temp->scalarval();

              $temp=$m->getParam(3);
              $token=$temp->scalarval();
              /*
              if ( $username == "xtest2")
               {
                    //$arrX["user"] = "0879114114"; //"102";
                    $arrX["user"] = "102";
                    $arrX["password"] = "100_WEjhjgyyte111";
                    $arrX["domain"] = "14.1.28.210";
                    $arrX["sipchat"] = "http://14.1.28.210/im";
                    $arrX["url_home"] = "https://vndig.com";
                    $arrX["url_services"] = "https://vndig.com";
                    $arrX["transport"] = "UDP";
                    $arrX["xmppserver"] = "http://comm.lotus-asia.net";
                    $arrX["liveserver"] = "rtmp://vndig.com/show/";
                    $arrX["signalserver"] = "https://vndig.com/signal/index.php";
                    $arrX["apisecret"] = "123sAAAA";
                    $arrX["socialurl"] = "http://social.onephone.online";
                    $arrX["shopurl"] = "http://shops.onephone.online";
                    $arrX["shopapisecret"] = "api123";
                    $arrX["certpayment"] = "kgakbj@#$#$#kkwqhkwqkjr23423jkwqgrkwqgrkqwrwqrqw";
                    $arrX["status"] = "OK";
                    
                    return new xmlrpcresp(new xmlrpcval(json_encode($arrX), "string"));
               
               }
              */
		$ret = "OK";	//"ERROR_ACCOUNT_ALREADY_ACTIVATED";
		$arrX = array();

		$arrX = errorDefault($username." ".$password);
		$access_token =  "aYDLsN8GrF4WrjisMvSUbzP3";
		$curl = new Curl();
		$curl->get('http://vndig.com/social/index.php', array(
		    		'r' => 'api/user/login',
		    		'access_token' => $access_token,
		    		'username' => $username,
		    		'password' => $password,
				));
		$c_userid = -1;
		$c_guid  = "";
		if ($curl->error) {
		    		//error_log( 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n");
				$arrX = errorDefault($username." ".$password." -LOGIN");
				return new xmlrpcresp(new xmlrpcval(json_encode($arrX), "string"));
				exit;		
		} else {
		    		error_log( 'Response: (NO ERROR)' . "\n");
				//error_log(print_r($curl->response,true));

				$c_userid  =$curl->response->id;
				$c_guid = $curl->response->guid;
		}
		if ( (  $c_guid == "" ) || (  $c_guid == "" ) )
		{
		    		//error_log( 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n");
				$arrX = errorDefault($username." ".$password." -LOGIN-FAIL");
				return new xmlrpcresp(new xmlrpcval(json_encode($arrX), "string"));
				exit;		
		}

		$c_onephone  = "";
		$c_guid = str_replace("-","",$c_guid);
        $c_guid = substr($c_guid,0,10);
		error_log(print_r($c_guid,true));
		$curl->get('http://vndig.com/social/index.php', array(
			    'r' => 'api/profile/view',
			    'access_token' => $access_token,
			    'id' => $c_userid,
			));
		if ($curl->error) {
		    		error_log( 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n");
				$arrX = errorDefault($username." ".$password." -PROFILE");
				return new xmlrpcresp(new xmlrpcval(json_encode($arrX), "string"));

				exit;		
		} else {
			    	error_log( 'Response:' . "\n");
				error_log(print_r($curl->response,true));
				$c_onephone = $curl->response->onephone;
		}
		$arrX["user"] = $c_onephone;
		$arrX["password"] = $c_guid;
		//$arrX["domain"] = "globalsip.lotus-asia.net:5070";
        //$arrX["domain"] = "sip.vndig.com:5060"; 14.1.28.210
        $arrX["domain"] = "14.1.28.210"; 
        $arrX["sipchat"] = "http://vndig.com/im/";
		//$arrX["sipchat"] = "http://globalsip.lotus-asia.net/im/";
		$arrX["url_home"] = "https://vndig.com";
		$arrX["url_services"] = "http://device.onephone.online";
		$arrX["transport"] = "UDP";
		$arrX["xmppserver"] = "http://comm.lotus-asia.net";
		$arrX["liveserver"] = "rtmp://vndig.com/show/";
			$arrX["signalserver"] = "https://vndig.com/signal/index.php";
			$arrX["apisecret"] = "123sAAAA";
			$arrX["socialurl"] = "http://social.onephone.online";
			$arrX["shopurl"] = "http://shops.onephone.online";
			$arrX["shopapisecret"] = "api123";
			$arrX["certpayment"] = "kgakbj@#$#$#kkwqhkwqkjr23423jkwqgrkwqgrkqwrwqrqw";
		$arrX["status"] = "OK";
error_log(print_r($arrX,true));        
		return new xmlrpcresp(new xmlrpcval(json_encode($arrX), "string"));
	}


         function date_convert($d)
         {
         //echo "<br>".$d."<br>";
         //$d = dd/mm/106
                  $da = explode("/", $d);
                  if ( ( $da[2] >= 100) && ($da[2] < 2000) ) $da[2] = ($da[2] - 100) + 2000;
                  if ( ( $da[2] < 100)  ) $da[2] = $da[2] + 2000;
                  if ( strlen($da[1]) == 1)  $da[1] = "0".$da[1];
                  if ( strlen($da[0]) == 1)  $da[0] = "0".$da[0];
                  $date1 = $da[2]."-".$da[1]."-".$da[0]." 00:00:00";
                  //echo "<br>".$date1."<br>";
                  return $date1;
       }
        /**
        * Inner code of the state-number server.
        * Used to test auto-registration of PHP funcions as xmlrpc methods.
        * @param integer $stateno the state number
        * @return string the name of the state (or error descrption)
        */
	ini_set('error_reporting', E_STRICT);

	date_default_timezone_set('Asia/Ho_Chi_Minh');

        $o=new xmlrpc_server_methods_container();
        $a=array(
                "onephone_android_login" => array(
                        "function" => "onephone_android_login",
                        "signature" => $onephone_android_login_sig,
                        "docstring" => $onephone_android_login_doc
                ),
                "onephone_iphone_login" => array(
                        "function" => "onephone_iphone_login",
                        "signature" => $onephone_iphone_login_sig,
                        "docstring" => $onephone_iphone_login_doc
                ),
        );
        $s=new xmlrpc_server($a, false);
        $s->setdebug(3);
//        $s->setdebug(0);
        $s->compress_response = true;
//XML_RPC_Client::setAutoBase64(true);
        if (isset($_GET['RESPONSE_ENCODING']))
                $s->response_charset_encoding = $_GET['RESPONSE_ENCODING'];
//error_log("phpwarninggeneratorXXXX ".print_r($s,true));
        $s->service();
        // that should do all we need!
?>